#!/usr/bin/env fish

# Change to the script's directory for now, it makes things easier.
set -l ambient_path (dirname (status --current-filename))
cd $ambient_path

# Accumulate non-empty KEY=VALUE pairs output from subscripts.
for kv in (./lib/_dispatch_ambient.fish)
    if test -z "$kv"
        continue
    end
    set -a environment $kv
end

# If arguments are given, call it as a command, with ambient data in the environment.
if [ (count $argv) -gt 0 ]
    env $environment $argv
else
    for kv in $environment
        echo $kv
    end
end
