#!/usr/bin/env fish

# Change to the script's directory for now, it makes things easier.
set -l ambient_path (dirname (status --current-filename))
cd $ambient_path

# Make fish autoload our functions before trying built-in ones.
set -p fish_function_path $ambient_path/functions.d

for file in ./ambient.d/**/*.fish
    source $file
end
