if set -q AMBIENT_AT_OEBB_STOP_NEXT
    echo " $AMBIENT_AT_OEBB_STOP_NEXT"
end
if [ -n "$AMBIENT_AT_OEBB_STOP_NEXT_ARRIVE_FORECAST" ]
    echo " $AMBIENT_AT_OEBB_STOP_NEXT_ARRIVE_FORECAST"
end
if set -q AMBIENT_AT_OEBB_TRAIN_TYPE
    echo " $AMBIENT_AT_OEBB_TRAIN_TYPE-$AMBIENT_AT_OEBB_VZN"
end
if set -q AMBIENT_AT_OEBB_SPEED
    echo " $AMBIENT_AT_OEBB_SPEED km/h"
end
