if set -q AMBIENT_DE_ICE_STOP_NEXT
    echo "$icons[1] $AMBIENT_DE_ICE_STOP_NEXT"
end
if [ -n "$AMBIENT_DE_ICE_STOP_NEXT_ARRIVE_DELAY" ]
	echo "$icons[2] $AMBIENT_DE_ICE_STOP_NEXT_ARRIVE_DELAY"
end
if set -q AMBIENT_DE_ICE_TRAIN_TYPE
	echo "$icons[3] $AMBIENT_DE_ICE_TRAIN_TYPE-$AMBIENT_DE_ICE_VZN"
end
if set -q AMBIENT_DE_ICE_SPEED
	echo "$icons[4] $AMBIENT_DE_ICE_SPEED km/h"
end
